spring.application.name=finance-tracker
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=20232171

# JPA settings
# Use the appropriate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update the database schema based on the entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console for debugging purposes
spring.jpa.show-sql=true

gemini.api.key=AIzaSyCTmQW0u8KtVqxOqm_04I7osvdjh1RO8h8
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent